In [2]:
import pandas as pd

pun = pd.read_excel(
    "data/companies.xlsx",
    header=None
)

pun.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,Mkt Fintech — Nifty 100 | Companies | 92 r...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
2,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10,1657,46,34.9
3,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10,175,9,8.59
4,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1,363,11.6,13.64

In [4]:
pd.read_csv("cleaned_data/companies.csv")

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
0,ABB,https://mkt.in/static/mkt-icons/nifty100/ABB.png,Abbott India Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Abbott India Ltd is one of the leading multina...,https://www.abbott.co.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/abb...,10.0,1657.0,46.0,34.90
1,ADANIENSOL,https://m.economictimes.com/thumb/msid-1173715...,Adani Energy Solutions Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"AESL, part of the Adani portfolio, is a multid...",https://www.adanienergysolutions.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,175.0,9.0,8.59
2,ADANIENT,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Enterprises Ltd,https://in.tradingview.com/chart/?symbol=ADANIENT,Adani Enterprises Ltd is an Indian multination...,https://www.adanienterprises.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,1.0,363.0,11.6,13.64
3,ADANIGREEN,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Green Energy Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,"Adani Green Energy Limited, incorporated in 20...",http://www.adanigreenenergy.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,10.0,67.0,96.5,14.70
4,ADANIPORTS,https://mkt.in/static/mkt-icons/nifty100/ADANI...,Adani Ports & Special Economic Zone Ltd\n,https://in.tradingview.com/chart/?symbol=NSE%3...,Adani Ports & Special Economic Zone is in the ...,http://www.adaniports.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/ada...,2.0,265.0,12.9,18.10
...,...,...,...,...,...,...,...,...,...,...,...,...
87,TECHM,https://mkt.in/static/mkt-icons/nifty100/TECHM...,Tech Mahindra Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,Tech Mahindra Ltd provides comprehensive range...,https://www.techmahindra.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/tec...,5.0,270.0,11.9,8.63
88,TITAN,https://mkt.in/static/mkt-icons/nifty100/TITAN...,Titan Company Ltd\n,https://in.tradingview.com/chart/qGsydD2w/?sym...,Titan Company Ltd is among India's most respec...,https://www.titancompany.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/tit...,1.0,110.0,22.7,32.90
89,TORNTPHARM,https://mkt.in/static/mkt-icons/nifty100/TORNT...,Torrent Pharmaceuticals Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,Torrent Pharmaceuticals Ltd is one of the lead...,https://www.torrentpharma.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/tor...,5.0,222.0,23.2,24.20
90,TRENT,https://mkt.in/static/mkt-icons/nifty100/TRENT...,Trent Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,"Trent Ltd is engaged in retailing of apparels,...",https://trentlimited.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/tre...,1.0,132.0,23.8,27.20
91,TVSMOTOR,https://mkt.in/static/mkt-icons/nifty100/TVSMO...,TVS Motor Company Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,'TVS Motor Company Ltd (TVSM) is engaged in ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
import pandas as pd
import numpy as np
import os

raw_path = "data/"
clean_path = "cleaned_data/"

os.makedirs(clean_path, exist_ok=True)

for file in os.listdir(raw_path):

    if not file.endswith(".xlsx"):
        continue

    print(f"Processing {file}")

    df = pd.read_excel(
        os.path.join(raw_path, file),
        skiprows=1,          # Skip title row
        engine="openpyxl"
    )

    # Clean column names
    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )

    # Convert NULL strings to NaN
    df.replace(
        ["NULL", "Null", "null", ""],
        np.nan,
        inplace=True
    )

    # Remove fully empty rows
    df.dropna(how="all", inplace=True)

    # Remove duplicate rows
    df.drop_duplicates(inplace=True)

    # Save cleaned file
    output_file = file.replace(".xlsx", ".csv")

    df.to_csv(
        os.path.join(clean_path, output_file),
        index=False
    )

    print(f"Saved -> cleaned_data/{output_file}")
    print(f"Shape -> {df.shape}")

print("All files cleaned successfully.")

Processing analysis.xlsx
Saved -> cleaned_data/analysis.csv
Shape -> (20, 6)
Processing balancesheet.xlsx
Saved -> cleaned_data/balancesheet.csv
Shape -> (1312, 13)
Processing cashflow.xlsx
Saved -> cleaned_data/cashflow.csv
Shape -> (1187, 7)
Processing companies.xlsx
Saved -> cleaned_data/companies.csv
Shape -> (92, 12)
Processing documents.xlsx
Saved -> cleaned_data/documents.csv
Shape -> (1585, 4)
Processing profitandloss.xlsx
Saved -> cleaned_data/profitandloss.csv
Shape -> (1276, 15)
Processing prosandcons.xlsx
Saved -> cleaned_data/prosandcons.csv
Shape -> (16, 4)
All files cleaned successfully.

In [1]:
import pandas as pd

analysis = pd.read_csv("data/clean/analysis.csv")

print(
    analysis[
        analysis["company_id"]
        .astype(str)
        .str.upper()
        .str.contains("WIPRO")
    ]
)

    id company_id compounded_sales_growth compounded_profit_growth  \
8   17      WIPRO        10 Years:     8%    10 Years:          3%
9   18      WIPRO       5 Years:       9%   5 Years:            4%
10  19      WIPRO       3 Years:      13%   3 Years:            0%
12  20      WIPRO      TTM:           -3%  TTM:                 1%

           stock_price_cagr                    roe
8         10 Years:     12%   10 Years:        18%
9          5 Years:     20%  5 Years:          17%
10        3 Years:      -1%  3 Years:          17%
12        1 Year:       39%   Last Year:       14%

In [2]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")
analysis = pd.read_csv("data/clean/analysis.csv")

companies = companies.rename(columns={"id": "company_id"})

companies["company_id"] = (
    companies["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

analysis["company_id"] = (
    analysis["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

missing = set(analysis["company_id"]) - set(companies["company_id"])

print("Missing IDs:")
print(sorted(missing))

Missing IDs:
['WIPRO']

In [3]:
companies[
    companies["company_id"]
    .str.contains("WIPRO", case=False, na=False)
]

Empty DataFrame
Columns: [company_id, company_logo, company_name, chart_link, about_company, website, nse_profile, bse_profile, face_value, book_value, roce_percentage, roe_percentage]
Index: []

In [4]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

for col in companies.columns:
    mask = (
        companies[col]
        .astype(str)
        .str.upper()
        .str.contains("WIPRO", na=False)
    )

    if mask.any():
        print(f"\nFound in column: {col}")
        print(companies[mask])

In [5]:
companies = pd.read_csv("data/clean/companies.csv")

print(companies.shape)
print(companies.tail(20))

(92, 12)
            id                                       company_logo  \
72         PNB   https://mkt.in/static/mkt-icons/nifty100/PNB.png
73   POWERGRID  https://mkt.in/static/mkt-icons/nifty100/POWER...
74      RECLTD  https://mkt.in/static/mkt-icons/nifty100/RECLT...
75    RELIANCE  https://mkt.in/static/mkt-icons/nifty100/RELIA...
76     SBILIFE  https://mkt.in/static/mkt-icons/nifty100/SBILI...
77        SBIN  https://mkt.in/static/mkt-icons/nifty100/SBIN.png
78    SHREECEM  https://mkt.in/static/mkt-icons/nifty100/SHREE...
79  SHRIRAMFIN  https://mkt.in/static/mkt-icons/nifty100/SHRIR...
80     SIEMENS  https://mkt.in/static/mkt-icons/nifty100/SIEME...
81   SUNPHARMA  https://mkt.in/static/mkt-icons/nifty100/SUNPH...
82  TATACONSUM  https://mkt.in/static/mkt-icons/nifty100/TATAC...
83  TATAMOTORS  https://mkt.in/static/mkt-icons/nifty100/TATAM...
84   TATAPOWER  https://mkt.in/static/mkt-icons/nifty100/TATAP...
85   TATASTEEL  https://mkt.in/static/mkt-icons/nifty100/TATAS...
86         TCS      https://images.5paisa.com/MarketIcons/TCS.png
87       TECHM  https://mkt.in/static/mkt-icons/nifty100/TECHM...
88       TITAN  https://mkt.in/static/mkt-icons/nifty100/TITAN...
89  TORNTPHARM  https://mkt.in/static/mkt-icons/nifty100/TORNT...
90       TRENT  https://mkt.in/static/mkt-icons/nifty100/TRENT...
91    TVSMOTOR  https://mkt.in/static/mkt-icons/nifty100/TVSMO...

                           company_name  \
72                 Punjab National Bank
73  Power Grid Corporation of India Ltd
74                              REC Ltd
75            Reliance Industries Ltd\n
76       SBI Life Insurance Company Ltd
77                  State Bank of India
78                     Shree Cement Ltd
79                Shriram Finance Ltd\n
80                          Siemens Ltd
81   Sun Pharmaceuticals Industries Ltd
82           Tata Consumer Products Ltd
83                      Tata Motors Ltd
84             Tata Power Company Ltd\n
85                     Tata Steel Ltd\n
86        Tata Consultancy Services Ltd
87                    Tech Mahindra Ltd
88                  Titan Company Ltd\n
89          Torrent Pharmaceuticals Ltd
90                            Trent Ltd
91                TVS Motor Company Ltd

                                           chart_link  \
72  https://in.tradingview.com/chart/?symbol=NSE%3...
73  https://in.tradingview.com/chart/qGsydD2w/?sym...
74  https://in.tradingview.com/chart/qGsydD2w/?sym...
75  https://in.tradingview.com/chart/qGsydD2w/?sym...
76  https://in.tradingview.com/chart/qGsydD2w/?sym...
77  https://in.tradingview.com/chart/qGsydD2w/?sym...
78  https://in.tradingview.com/chart/qGsydD2w/?sym...
79  https://in.tradingview.com/chart/qGsydD2w/?sym...
80  https://in.tradingview.com/chart/qGsydD2w/?sym...
81  https://in.tradingview.com/chart/qGsydD2w/?sym...
82  https://in.tradingview.com/chart/qGsydD2w/?sym...
83  https://in.tradingview.com/chart/qGsydD2w/?sym...
84  https://in.tradingview.com/chart/qGsydD2w/?sym...
85  https://in.tradingview.com/chart/qGsydD2w/?sym...
86  https://www.tradingview.com/chart/?symbol=NSE%...
87  https://in.tradingview.com/chart/qGsydD2w/?sym...
88  https://in.tradingview.com/chart/qGsydD2w/?sym...
89  https://in.tradingview.com/chart/qGsydD2w/?sym...
90  https://in.tradingview.com/chart/qGsydD2w/?sym...
91  https://in.tradingview.com/chart/qGsydD2w/?sym...

                                        about_company  \
72  Punjab National Bank is an Indian government b...
73  Power Grid Corporation of India Limited is a M...
74  REC is a Central Public Sector Undertaking und...
75  Reliance was founded by Dhirubhai Ambani and i...
76  SBI Life Insurance Company Ltd is engaged in t...
77  State Bank of India is a Fortune 500 company. ...
78  Shree Cement is engaged in manufacturing and s...
79  Business Overview\nShriram Transport Finance C...
80  Siemens Limited offers products, integrated so...
81  Sun Pharmaceutical Industries Ltd is engaged i...
82  Tata Consumer Products Ltd. is one of the lead...
83  Tata Motors Group is a leading global automobi...
84  Tata Power Company Ltd is primarily involved i...
85  Tata Steel Ltd is Asia's first integrated priv...
86  Tata Consultancy Services is the flagship comp...
87  Tech Mahindra Ltd provides comprehensive range...
88  Titan Company Ltd is among India's most respec...
89  Torrent Pharmaceuticals Ltd is one of the lead...
90  Trent Ltd is engaged in retailing of apparels,...
91  'TVS Motor Company Ltd (TVSM) is engaged in ma...

                               website  \
72            https://www.pnbindia.in/
73           https://www.powergrid.in/
74            https://recindia.nic.in/
75                https://www.ril.com/
76          https://www.sbilife.co.in/
77                  https://sbi.co.in/
78        https://www.shreecement.com/
79      https://www.shriramfinance.in/
80  https://www.siemens.com/in/en.html
81              https://sunpharma.com/
82       https://www.tataconsumer.com/
83         https://www.tatamotors.com/
84          https://www.tatapower.com/
85          https://www.tatasteel.com/
86                https://www.tcs.com/
87       https://www.techmahindra.com/
88        https://www.titancompany.in/
89      https://www.torrentpharma.com/
90           https://trentlimited.com/
91                                 NaN

                                          nse_profile  \
72  https://www.nseindia.com/get-quotes/equity?sym...
73  https://www.nseindia.com/get-quotes/equity?sym...
74  https://www.nseindia.com/get-quotes/equity?sym...
75  https://www.nseindia.com/get-quotes/equity?sym...
76  https://www.nseindia.com/get-quotes/equity?sym...
77  https://www.nseindia.com/get-quotes/equity?sym...
78  https://www.nseindia.com/get-quotes/equity?sym...
79  https://www.nseindia.com/get-quotes/equity?sym...
80  https://www.nseindia.com/get-quotes/equity?sym...
81  https://www.nseindia.com/get-quotes/equity?sym...
82  https://www.nseindia.com/get-quotes/equity?sym...
83  https://www.nseindia.com/get-quotes/equity?sym...
84  https://www.nseindia.com/get-quotes/equity?sym...
85  https://www.nseindia.com/get-quotes/equity?sym...
86  https://www.nseindia.com/get-quotes/equity?sym...
87  https://www.nseindia.com/get-quotes/equity?sym...
88  https://www.nseindia.com/get-quotes/equity?sym...
89  https://www.nseindia.com/get-quotes/equity?sym...
90  https://www.nseindia.com/get-quotes/equity?sym...
91                                                NaN

                                          bse_profile  face_value  book_value  \
72  https://www.bseindia.com/stock-share-price/pun...         2.0       110.0
73  https://www.bseindia.com/stock-share-price/pow...        10.0        99.0
74  https://www.bseindia.com/stock-share-price/rec...        10.0       279.0
75  https://www.bseindia.com/stock-share-price/rel...        10.0       606.0
76  https://www.bseindia.com/stock-share-price/sbi...        10.0       162.0
77  https://www.bseindia.com/stock-share-price/sta...         1.0       465.0
78  https://www.bseindia.com/stock-share-price/shr...        10.0      5787.0
79  https://www.bseindia.com/stock-share-price/shr...         2.0       279.0
80  https://www.bseindia.com/stock-share-price/sie...         2.0       431.0
81  https://www.bseindia.com/stock-share-price/sun...         1.0       288.0
82  https://www.bseindia.com/stock-share-price/tat...         1.0       193.0
83  https://www.bseindia.com/stock-share-price/tat...         2.0       275.0
84  https://www.bseindia.com/stock-share-price/tat...         1.0       105.0
85  https://www.bseindia.com/stock-share-price/tat...         1.0        72.0
86  https://www.bseindia.com/stock-share-price/tat...         1.0       281.0
87  https://www.bseindia.com/stock-share-price/tec...         5.0       270.0
88  https://www.bseindia.com/stock-share-price/tit...         1.0       110.0
89  https://www.bseindia.com/stock-share-price/tor...         5.0       222.0
90  https://www.bseindia.com/stock-share-price/tre...         1.0       132.0
91                                                NaN         NaN         NaN

    roce_percentage  roe_percentage
72             1.63            8.70
73            13.20           19.00
74            10.00           22.20
75             9.61            9.25
76            13.20           12.00
77             6.16           17.30
78            14.80           12.20
79            11.30           15.90
80            25.60           19.10
81            17.30           16.70
82            10.60            8.32
83            20.10           49.40
84            11.10           11.30
85             7.02            6.55
86            64.30            0.52
87            11.90            8.63
88            22.70           32.90
89            23.20           24.20
90            23.80           27.20
91              NaN             NaN

In [6]:
raw = pd.read_excel("data/companies.xlsx")

print(
    raw[
        raw.astype(str)
        .apply(lambda x: x.str.contains("WIPRO", case=False, na=False))
        .any(axis=1)
    ]
)

Empty DataFrame
Columns: [Mkt Fintech — Nifty 100  |  Companies  |  92 records, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []

In [8]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

print(companies.columns.tolist())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

In [9]:
import pandas as pd

files = [
    "analysis.csv",
    "balancesheet.csv",
    "cashflow.csv",
    "profitandloss.csv",
    "prosandcons.csv",
    "documents.csv"
]

for file in files:

    df = pd.read_csv(f"data/clean/{file}")

    if "company_id" not in df.columns:
        continue

    exists = (
        df["company_id"]
        .astype(str)
        .str.upper()
        .eq("WIPRO")
        .any()
    )

    print(file, exists)

analysis.csv True
balancesheet.csv True
cashflow.csv True
profitandloss.csv True
prosandcons.csv True
documents.csv True

In [10]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

companies_ids = set(
    companies["id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

analysis = pd.read_csv("data/clean/analysis.csv")

analysis_ids = set(
    analysis["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

print(sorted(analysis_ids - companies_ids))

['WIPRO']

In [11]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

print(companies.shape)

print(
    companies[
        companies["id"]
        .astype(str)
        .str.upper()
        .eq("WIPRO")
    ]
)

(92, 12)
Empty DataFrame
Columns: [id, company_logo, company_name, chart_link, about_company, website, nse_profile, bse_profile, face_value, book_value, roce_percentage, roe_percentage]
Index: []

In [12]:
import pandas as pd

raw = pd.read_excel("data/companies.xlsx")

print(raw.shape)
print(raw.head())

(93, 12)
  Mkt Fintech — Nifty 100  |  Companies  |  92 records  \
0                                                 id
1                                                ABB
2                                         ADANIENSOL
3                                           ADANIENT
4                                         ADANIGREEN

                                          Unnamed: 1  \
0                                       company_logo
1   https://mkt.in/static/mkt-icons/nifty100/ABB.png
2  https://m.economictimes.com/thumb/msid-1173715...
3  https://mkt.in/static/mkt-icons/nifty100/ADANI...
4  https://mkt.in/static/mkt-icons/nifty100/ADANI...

                   Unnamed: 2  \
0                company_name
1            Abbott India Ltd
2  Adani Energy Solutions Ltd
3       Adani Enterprises Ltd
4      Adani Green Energy Ltd

                                          Unnamed: 3  \
0                                         chart_link
1  https://in.tradingview.com/chart/?symbol=NSE%3...
2  https://in.tradingview.com/chart/?symbol=NSE%3...
3  https://in.tradingview.com/chart/?symbol=ADANIENT
4  https://in.tradingview.com/chart/?symbol=NSE%3...

                                          Unnamed: 4  \
0                                      about_company
1  Abbott India Ltd is one of the leading multina...
2  AESL, part of the Adani portfolio, is a multid...
3  Adani Enterprises Ltd is an Indian multination...
4  Adani Green Energy Limited, incorporated in 20...

                              Unnamed: 5  \
0                                website
1              https://www.abbott.co.in/
2  https://www.adanienergysolutions.com/
3      https://www.adanienterprises.com/
4       http://www.adanigreenenergy.com/

                                          Unnamed: 6  \
0                                        nse_profile
1  https://www.nseindia.com/get-quotes/equity?sym...
2  https://www.nseindia.com/get-quotes/equity?sym...
3  https://www.nseindia.com/get-quotes/equity?sym...
4  https://www.nseindia.com/get-quotes/equity?sym...

                                          Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0                                        bse_profile  face_value  book_value
1  https://www.bseindia.com/stock-share-price/abb...          10        1657
2  https://www.bseindia.com/stock-share-price/ada...          10         175
3  https://www.bseindia.com/stock-share-price/ada...           1         363
4  https://www.bseindia.com/stock-share-price/ada...          10          67

       Unnamed: 10     Unnamed: 11
0  roce_percentage  roe_percentage
1               46            34.9
2                9            8.59
3             11.6           13.64
4             96.5            14.7

In [13]:
import pandas as pd

raw = pd.read_excel("data/companies.xlsx")

print(
    raw[
        raw.astype(str)
        .apply(lambda x: x.str.contains("WIPRO", case=False, na=False))
        .any(axis=1)
    ]
)

Empty DataFrame
Columns: [Mkt Fintech — Nifty 100  |  Companies  |  92 records, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11]
Index: []

In [14]:
import pandas as pd

analysis = pd.read_csv("data/clean/analysis.csv")
companies = pd.read_csv("data/clean/companies.csv")

company_ids = set(
    companies["id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

analysis_ids = set(
    analysis["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

missing = sorted(analysis_ids - company_ids)

print(missing)
print("Missing count:", len(missing))

['WIPRO']
Missing count: 1

In [15]:
import pandas as pd

df = pd.read_csv("data/clean/balancesheet.csv")
print(df.columns.tolist())

['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

In [16]:
for f in [
    "balancesheet.csv",
    "cashflow.csv",
    "profitandloss.csv",
    "documents.csv"
]:
    df = pd.read_csv(f"data/clean/{f}")
    print(f)
    print(df.columns.tolist())
    print()

balancesheet.csv
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

cashflow.csv
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

profitandloss.csv
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

documents.csv
['id', 'company_id', 'year', 'annual_report']

In [17]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

for c in [
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "VEDL",
    "ZOMATO",
    "ZYDUSLIFE"
]:
    print(c, c in companies["id"].astype(str).str.upper().values)

ULTRACEMCO False
UNIONBANK False
UNITDSPR False
VEDL False
ZOMATO False
ZYDUSLIFE False

In [18]:
import pandas as pd

bs = pd.read_csv("data/clean/balancesheet.csv")

for c in [
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "VEDL",
    "ZOMATO",
    "ZYDUSLIFE"
]:
    print(bs[bs["company_id"] == c].head(1))

        id  company_id      year  equity_capital  reserves  borrowings  \
1156  1323  ULTRACEMCO  Mar 2013           274.0     14955        7342

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1156               7010              29582         15050  3601         4709

      other_asset  total_assets
1156         6222         29582
        id company_id      year  equity_capital  reserves  borrowings  \
1131  1298  UNIONBANK  Mar 2013           597.0     16722      287589

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1131               8003             312912          2483    13        81808

      other_asset  total_assets
1131       228608        312912
        id company_id  year  equity_capital  reserves  borrowings  \
1118  1285   UNITDSPR  2013           126.0      4661        8242

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1118               3453              16483          7869   131          218

      other_asset  total_assets
1118         8265         16483
        id company_id  year  equity_capital  reserves  borrowings  \
1080  1247       VEDL  2013            87.0     17388        4839

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1080                723              23037          4136   723        16059

      other_asset  total_assets
1080         2119         23037
        id company_id  year  equity_capital  reserves  borrowings  \
1059  1226     ZOMATO  2018             0.0      1036         186

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1059                152               1374           190     1          829

      other_asset  total_assets
1059          354          1374
        id company_id  year  equity_capital  reserves  borrowings  \
1033  1200  ZYDUSLIFE  2013           102.0      2842        2918

      other_liabilities  total_liabilities  fixed_assets  cwip  investments  \
1033               1512               7374          3026   736          114

      other_asset  total_assets
1033         3498          7374

In [19]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")
companies = companies.rename(columns={"id": "company_id"})

company_ids = set(
    companies["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

for file in [
    "balancesheet.csv",
    "cashflow.csv",
    "profitandloss.csv",
    "analysis.csv",
    "prosandcons.csv",
    "documents.csv"
]:
    df = pd.read_csv(f"data/clean/{file}")

    if "company_id" in df.columns:
        ids = set(
            df["company_id"]
            .astype(str)
            .str.strip()
            .str.upper()
        )

        missing = ids - company_ids

        print("\n", file)
        print(sorted(missing))

 balancesheet.csv
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

 cashflow.csv
['AGTL', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

 profitandloss.csv
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

 analysis.csv
['WIPRO']

 prosandcons.csv
['WIPRO']

 documents.csv
['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']

In [20]:
companies = pd.read_csv("data/clean/companies.csv")
companies = companies.rename(columns={"id":"company_id"})

In [21]:
required_ids = {
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "VEDL",
    "WIPRO",
    "ZOMATO",
    "ZYDUSLIFE",
    "VBL",
    "AGTL"
}

existing_ids = set(
    companies["company_id"]
    .astype(str)
    .str.strip()
    .str.upper()
)

missing = required_ids - existing_ids

for cid in missing:
    companies.loc[len(companies)] = {
        "company_id": cid,
        "company_name": cid
    }

print("Added missing companies:", missing)

Added missing companies: {'VEDL', 'ULTRACEMCO', 'UNIONBANK', 'VBL', 'UNITDSPR', 'WIPRO', 'ZYDUSLIFE', 'ZOMATO', 'AGTL'}

In [22]:
fact_files = [
    "analysis.csv",
    "balancesheet.csv",
    "cashflow.csv",
    "profitandloss.csv",
    "prosandcons.csv",
    "documents.csv"
]

valid_ids = set(companies["company_id"])

for file in fact_files:

    df = pd.read_csv(f"data/clean/{file}")

    missing = set(
        df["company_id"]
        .astype(str)
        .str.strip()
        .str.upper()
    ) - valid_ids

    print(file, missing)

analysis.csv set()
balancesheet.csv set()
cashflow.csv set()
profitandloss.csv set()
prosandcons.csv set()
documents.csv set()

In [23]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

companies = companies.rename(columns={"id": "company_id"})

for company in [
    "AGTL",
    "VBL",
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "VEDL",
    "ZOMATO",
    "ZYDUSLIFE"
]:
    print(company, company in companies["company_id"].values)

AGTL False
VBL False
ULTRACEMCO False
UNIONBANK False
UNITDSPR False
VEDL False
ZOMATO False
ZYDUSLIFE False

In [24]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

new_companies = pd.DataFrame({
    "id": [
        "AGTL",
        "VBL",
        "ULTRACEMCO",
        "UNIONBANK",
        "UNITDSPR",
        "VEDL",
        "ZOMATO",
        "ZYDUSLIFE"
    ],
    "company_name": [
        "Adani Total Gas Ltd",
        "Varun Beverages Ltd",
        "UltraTech Cement Ltd",
        "Union Bank of India",
        "United Spirits Ltd",
        "Vedanta Ltd",
        "Zomato Ltd",
        "Zydus Lifesciences Ltd"
    ]
})

companies = pd.concat([companies, new_companies], ignore_index=True)

companies.to_csv("data/clean/companies.csv", index=False)

print("Added missing companies")

Added missing companies

In [25]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

for c in [
    "AGTL","VBL","ULTRACEMCO","UNIONBANK",
    "UNITDSPR","VEDL","ZOMATO","ZYDUSLIFE"
]:
    print(c, c in companies["id"].values)

AGTL True
VBL True
ULTRACEMCO True
UNIONBANK True
UNITDSPR True
VEDL True
ZOMATO True
ZYDUSLIFE True

In [26]:
import pandas as pd

print(pd.read_csv("data/clean/analysis.csv").shape)
print(pd.read_csv("data/clean/prosandcons.csv").shape)

(20, 6)
(16, 4)

In [27]:
import pandas as pd

analysis = pd.read_csv("data/clean/analysis.csv")
print(sorted(analysis["company_id"].unique()))

['HDFCBANK', 'INFY', 'SBILIFE', 'TCS', 'WIPRO']

In [31]:
print(analysis.head(20))

    id company_id          compounded_sales_growth  compounded_profit_growth  \
0    1   HDFCBANK                    10 Years: 21%             10 Years: 22%
1   10    SBILIFE               5 Years:       24%    5 Years:            6%
2   11    SBILIFE               3 Years:       17%    3 Years:            9%
3   12    SBILIFE              TTM:            43%  TTM:                 18%
4   13        TCS   10 Years:     11%                  10 Years:          9%
5   14        TCS  5 Years:       10%                 5 Years:            8%
6   15        TCS  3 Years:       14%                3 Years:            12%
7   16        TCS  TTM:            5%                TTM:                 8%
8   17      WIPRO                 10 Years:     8%     10 Years:          3%
9   18      WIPRO                5 Years:       9%    5 Years:            4%
10  19      WIPRO                3 Years:      13%    3 Years:            0%
11   2   HDFCBANK               5 Years:       22%    5 Years:           23%
12  20      WIPRO               TTM:           -3%   TTM:                 1%
13   3   HDFCBANK               3 Years:       30%    3 Years:           26%
14   4   HDFCBANK              TTM:            47%   TTM:                27%
15   5       INFY                10 Years:     12%      10 Years:         9%
16   6       INFY               5 Years:       13%    5 Years:           11%
17   7       INFY                3 Years:       5%    3 Years:           10%
18   8       INFY               TTM:            3%   TTM:                 8%
19   9    SBILIFE                10 Years:     23%     10 Years:          9%

            stock_price_cagr                    roe
0          10 Years:     15%      10 Years:     17%
1          5 Years:       8%   5 Years          14%
2          3 Years:       7%   3 Years:         13%
3        1 Year:         -2%    Last Year:      12%
4         10 Years:      14%    10 Years:       40%
5          5 Years:      16%  5 Years:          44%
6           3 Years:      8%  3 Years:          47%
7          1 Year:       16%   Last Year:       52%
8          10 Years:     12%   10 Years:        18%
9           5 Years:     20%  5 Years:          17%
10         3 Years:      -1%  3 Years:          17%
11         5 Years:       8%     5 Years:       17%
12         1 Year:       39%   Last Year:       14%
13         3 Years:       8%     3 Years:       17%
14        1 Year:        13%      Last Year:    17%
15         10 Years:     15%     10 Years:      27%
16          5 Years:     22%    5 Years:        29%
17           3 Years:     4%    3 Years:        31%
18         1 Year:       27%     Last Year:     32%
19         10 Years:      9%     10 Years:      16%

In [28]:
import pandas as pd

pros = pd.read_csv("data/clean/prosandcons.csv")
print(sorted(pros["company_id"].unique()))

['HDFCBANK', 'INFY', 'SBILIFE', 'TCS', 'WIPRO']

In [29]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")
companies = companies.rename(columns={"id": "company_id"})

all_companies = set(companies["company_id"])

analysis = pd.read_csv("data/clean/analysis.csv")

missing = sorted(
    all_companies - set(analysis["company_id"])
)

print("Missing from analysis:")
print(missing)
print("Count:", len(missing))

Missing from analysis:
['ABB', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AGTL', 'AMBUJACEM', 'APOLLOHOSP', 'ASIANPAINT', 'ATGL', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BEL', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'DABUR', 'DIVISLAB', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'INDIGO', 'INDUSINDBK', 'IOC', 'IRCTC', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'KOTAKBANK', 'LICI', 'LODHA', 'LT', 'LTIM', 'M&M', 'MARUTI', 'MOTHERSON', 'NAUKRI', 'NESTLEIND', 'NHPC', 'NTPC', 'ONGC', 'PFC', 'PIDILITIND', 'PNB', 'POWERGRID', 'RECLTD', 'RELIANCE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TECHM', 'TITAN', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'ZOMATO', 'ZYDUSLIFE']
Count: 96

In [30]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")
companies = companies.rename(columns={"id": "company_id"})

pros = pd.read_csv("data/clean/prosandcons.csv")

missing = sorted(
    set(companies["company_id"]) -
    set(pros["company_id"])
)

print("Missing from pros_cons:")
print(missing)
print("Count:", len(missing))

Missing from pros_cons:
['ABB', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS', 'ADANIPOWER', 'AGTL', 'AMBUJACEM', 'APOLLOHOSP', 'ASIANPAINT', 'ATGL', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAJHLDNG', 'BAJFINANCE', 'BANKBARODA', 'BEL', 'BHARTIARTL', 'BHEL', 'BOSCHLTD', 'BPCL', 'BRITANNIA', 'CANBK', 'CHOLAFIN', 'CIPLA', 'COALINDIA', 'DABUR', 'DIVISLAB', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GODREJCP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCLIFE', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'ICICIGI', 'ICICIPRULI', 'INDIGO', 'INDUSINDBK', 'IOC', 'IRCTC', 'IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'KOTAKBANK', 'LICI', 'LODHA', 'LT', 'LTIM', 'M&M', 'MARUTI', 'MOTHERSON', 'NAUKRI', 'NESTLEIND', 'NHPC', 'NTPC', 'ONGC', 'PFC', 'PIDILITIND', 'PNB', 'POWERGRID', 'RECLTD', 'RELIANCE', 'SBIN', 'SHREECEM', 'SHRIRAMFIN', 'SIEMENS', 'SUNPHARMA', 'TATACONSUM', 'TATAMOTORS', 'TATAPOWER', 'TATASTEEL', 'TECHM', 'TITAN', 'TORNTPHARM', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'ZOMATO', 'ZYDUSLIFE']
Count: 96

In [44]:
import pandas as pd
import numpy as np
import os

# =========================
# PATHS
# =========================

INPUT_FOLDER = "data"
OUTPUT_FOLDER = "data/cleaned"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# =========================
# PROCESS ALL XLSX FILES
# =========================

for file in os.listdir(INPUT_FOLDER):

    if not file.endswith(".xlsx"):
        continue

    print(f"\nProcessing {file}")

    file_path = os.path.join(INPUT_FOLDER, file)

    # Read Excel
    df = pd.read_excel(
        file_path,
        header=1,  # your files have title row first
        engine="openpyxl"
    )

    # =========================
    # CLEAN COLUMN NAMES
    # =========================

    df.columns = (
        df.columns.astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
        .str.replace("/", "_", regex=False)
    )

    # =========================
    # REMOVE UNNAMED COLUMNS
    # =========================

    df = df.loc[
        :,
        ~df.columns.str.contains("^unnamed", case=False)
    ]

    # =========================
    # REPLACE NULL VALUES
    # =========================

    df.replace(
        ["NULL", "Null", "null", ""],
        np.nan,
        inplace=True
    )

    # =========================
    # STRIP STRING COLUMNS
    # =========================

    for col in df.columns:

        if df[col].dtype == "object":

            df[col] = (
                df[col]
                .astype(str)
                .str.strip()
            )

    # =========================
    # COMPANIES FILE SPECIAL FIX
    # =========================

    if file.lower() == "companies.xlsx":

        if "id" in df.columns:

            df.rename(
                columns={"id": "company_id"},
                inplace=True
            )

        if "company_id" in df.columns:

            df["company_id"] = (
                df["company_id"]
                .astype(str)
                .str.strip()
                .str.upper()
            )

    # =========================
    # OTHER FILES
    # =========================

    if "company_id" in df.columns:

        df["company_id"] = (
            df["company_id"]
            .astype(str)
            .str.strip()
            .str.upper()
        )

    # =========================
    # REMOVE EMPTY ROWS
    # =========================

    df.dropna(how="all", inplace=True)

    # =========================
    # REMOVE DUPLICATES
    # =========================

    df.drop_duplicates(inplace=True)

    # =========================
    # SAVE CSV
    # =========================

    output_file = file.replace(".xlsx", ".csv")

    output_path = os.path.join(
        OUTPUT_FOLDER,
        output_file
    )

    df.to_csv(
        output_path,
        index=False
    )

    print(f"Saved -> {output_path}")
    print(f"Rows -> {len(df)}")
    print(f"Columns -> {len(df.columns)}")

print("\nAll files converted successfully.")

Processing analysis.xlsx
Saved -> data/cleaned\analysis.csv
Rows -> 20
Columns -> 6

Processing balancesheet.xlsx
Saved -> data/cleaned\balancesheet.csv
Rows -> 1312
Columns -> 13

Processing cashflow.xlsx
Saved -> data/cleaned\cashflow.csv
Rows -> 1187
Columns -> 7

Processing companies.xlsx
Saved -> data/cleaned\companies.csv
Rows -> 92
Columns -> 12

Processing documents.xlsx
Saved -> data/cleaned\documents.csv
Rows -> 1585
Columns -> 4

Processing profitandloss.xlsx
Saved -> data/cleaned\profitandloss.csv
Rows -> 1276
Columns -> 15

Processing prosandcons.xlsx
Saved -> data/cleaned\prosandcons.csv
Rows -> 16
Columns -> 4

All files converted successfully.

In [37]:
import pandas as pd

companies = pd.read_csv("data/clean/companies.csv")

print(companies.columns.tolist())
print(companies.head())

['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']
           id                                       company_logo  \
0         ABB   https://mkt.in/static/mkt-icons/nifty100/ABB.png
1  ADANIENSOL  https://m.economictimes.com/thumb/msid-1173715...
2    ADANIENT  https://mkt.in/static/mkt-icons/nifty100/ADANI...
3  ADANIGREEN  https://mkt.in/static/mkt-icons/nifty100/ADANI...
4  ADANIPORTS  https://mkt.in/static/mkt-icons/nifty100/ADANI...

                                company_name  \
0                           Abbott India Ltd
1                 Adani Energy Solutions Ltd
2                      Adani Enterprises Ltd
3                     Adani Green Energy Ltd
4  Adani Ports & Special Economic Zone Ltd\n

                                          chart_link  \
0  https://in.tradingview.com/chart/?symbol=NSE%3...
1  https://in.tradingview.com/chart/?symbol=NSE%3...
2  https://in.tradingview.com/chart/?symbol=ADANIENT
3  https://in.tradingview.com/chart/?symbol=NSE%3...
4  https://in.tradingview.com/chart/?symbol=NSE%3...

                                       about_company  \
0  Abbott India Ltd is one of the leading multina...
1  AESL, part of the Adani portfolio, is a multid...
2  Adani Enterprises Ltd is an Indian multination...
3  Adani Green Energy Limited, incorporated in 20...
4  Adani Ports & Special Economic Zone is in the ...

                                 website  \
0              https://www.abbott.co.in/
1  https://www.adanienergysolutions.com/
2      https://www.adanienterprises.com/
3       http://www.adanigreenenergy.com/
4             http://www.adaniports.com/

                                         nse_profile  \
0  https://www.nseindia.com/get-quotes/equity?sym...
1  https://www.nseindia.com/get-quotes/equity?sym...
2  https://www.nseindia.com/get-quotes/equity?sym...
3  https://www.nseindia.com/get-quotes/equity?sym...
4  https://www.nseindia.com/get-quotes/equity?sym...

                                         bse_profile  face_value  book_value  \
0  https://www.bseindia.com/stock-share-price/abb...        10.0      1657.0
1  https://www.bseindia.com/stock-share-price/ada...        10.0       175.0
2  https://www.bseindia.com/stock-share-price/ada...         1.0       363.0
3  https://www.bseindia.com/stock-share-price/ada...        10.0        67.0
4  https://www.bseindia.com/stock-share-price/ada...         2.0       265.0

   roce_percentage  roe_percentage
0             46.0           34.90
1              9.0            8.59
2             11.6           13.64
3             96.5           14.70
4             12.9           18.10

In [45]:
import pandas as pd

analysis = pd.read_csv("data/cleaned/analysis.csv")

print("Rows:", len(analysis))
print("Unique companies:", analysis["company_id"].nunique())

print(analysis["company_id"].unique())

Rows: 20
Unique companies: 5
['HDFCBANK' 'SBILIFE' 'TCS' 'WIPRO' 'INFY']

In [46]:
import pandas as pd

pros = pd.read_csv("data/cleaned/prosandcons.csv")

print("Rows:", len(pros))
print("Unique companies:", pros["company_id"].nunique())
print(pros["company_id"].unique())

Rows: 16
Unique companies: 5
['HDFCBANK' 'SBILIFE' 'INFY' 'WIPRO' 'TCS']

In [47]:
import pandas as pd

df = pd.read_excel("data/analysis.xlsx", header=1)

print("Rows:", len(df))
print("Unique companies:", df["company_id"].nunique())
print(df["company_id"].unique())

Rows: 20
Unique companies: 5
['HDFCBANK' 'SBILIFE' 'TCS' 'WIPRO' 'INFY']

In [48]:
import pandas as pd

c1 = pd.read_csv("data/clean/companies.csv")
c2 = pd.read_csv("data/cleaned/companies.csv")

print("clean:", len(c1))
print("cleaned:", len(c2))

missing = set(c1["id"]) - set(c2["company_id"])
print("Missing:", sorted(missing))

clean: 100
cleaned: 92
Missing: ['AGTL', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'ZOMATO', 'ZYDUSLIFE']

In [49]:
import pandas as pd

df = pd.read_csv("data/clean/balancesheet.csv")

print(df.columns.tolist())

['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

In [50]:
import pandas as pd

df = pd.read_csv("data/clean/cashflow.csv")

print(df.columns.tolist())

['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

In [51]:
import pandas as pd

df = pd.read_csv("data/clean/profitandloss.csv")

print(df.columns.tolist())

['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

In [1]:
# Bluestock Analytics Dashboard | Power BI, PostgreSQL

# • Built an executive dashboard analyzing 100+ Indian listed companies.
# • Integrated PostgreSQL data with Power BI.
# • Developed interactive company-level drill-down reports with KPI cards, charts, filters, and company profiles.
# • Implemented sector-wise and company-wise performance analysis.